# Generated by Django 3.1 on 2022-11-01 18:45

from django.db import migrations, models
import status.models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=status.models.upload_status_image),
        ),
        migrations.AddField(
            model_name='status',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=status.models.upload_status_image),
        ),
    ]
